// TERRAIN
export const TERRAIN = [
    { 
        id: 1,
        name: 'Nyanyi',
        slug: "nyanyi-2.5are",
        price: '18.5',
        size: '2.5',
        time: 'Leasehold 30 ans',
        zone: 'Rose',
        image1: '/image/terrains/Nyanyi/2.5are/img1.jpg',
        img: '/image/terrains/Nyanyi/2.5are',
        totalImages: 4,
    },
    { 
        id: 2,
        name: 'Nyanyi',
        slug: "nyanyi-3are",
        price: '21.5',
        size: '3',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Nyanyi/3are/img1.jpg',
        img: '/image/terrains/Nyanyi/3are',
        totalImages: 4,
    },
    { 
        id: 3,
        name: 'Buwit',
        slug: "buwit-3.7are",
        price: '10',
        size: '3.7',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Buwit/3.7are/img1.jpg',
        image2: '/image/terrains/Buwit/3.7are/img2.jpg',
        image3: '/image/terrains/Buwit/3.7are/img2.jpg',
        img: '/image/terrains/Buwit/3.7are',
        totalImages: 3,
        status: 'vendu',
    },
    { 
        id: 4,
        name: 'Kaba Kaba',
        slug: "kaba-4are",
        price: '11.5',
        size: '4',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Kaba/4are/img1.jpg',
        img: '/image/terrains/Kaba/4are',
        totalImages: 4,
    },
    { 
        id: 5,
        name: 'Nyanyi',
        slug: "nyanyi-5are",
        price: '16.5',
        size: '5',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Nyanyi/5are/img1.jpg',
        img: '/image/terrains/Nyanyi/5are',
        totalImages: 4,
    },
    { 
        id: 6,
        name: 'Buwit',
        slug: "Buwit-5are",
        price: '10',
        size: '5',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Buwit/5are/img1.jpg',
        img: '/image/terrains/Buwit/5are',
        totalImages: 3,
    },
    { 
        id: 7,
        name: 'Kaba Kaba',
        slug: "kaba-6are",
        price: '10',
        size: '6',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/kaba/6are/img1.jpg',
        img: '/image/terrains/kaba/6are',
        totalImages: 4,
    },
    { 
        id: 8,
        name: 'Ubud',
        slug: "ubud-6.2are",
        price: '4',
        size: '6.2',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/ubud/6.2are/img1.jpg',
        img: '/image/terrains/ubud/6.2are',
        totalImages: 4,
    },
    { 
        id: 9,
        name: 'Ubud',
        slug: "ubud-7are",
        price: '4',
        size: '7',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/ubud/7are/img1.jpg',
        img: '/image/terrains/ubud/7are',
        totalImages: 4,
    },
    { 
        id: 10,
        name: 'Kaba Kaba',
        slug: "kaba-7are",
        price: '9.5',
        size: '7',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/kaba/7are-9.5mil/img1.jpg',
        img: '/image/terrains/kaba/7are-9.5mil',
        totalImages: 4,
    },
    { 
        id: 11,
        name: 'Kaba Kaba',
        slug: "kaba-7are",
        price: '12',
        size: '7',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/kaba/7are/img1.jpg',
        img: '/image/terrains/kaba/7are',
        totalImages: 4,
    },
    { 
        id: 12,
        name: 'Ubud',
        slug: "ubud-7.7are",
        price: '4',
        size: '7.7',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/ubud/7.7are/img1.jpg',
        img: '/image/terrains/ubud/7.7are',
        totalImages: 4,
    },
    { 
        id: 13,
        name: 'Ubud',
        slug: "ubud-8are",
        price: '4',
        size: '8',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/ubud/8are/img1.jpg',
        img: '/image/terrains/ubud/8are',
        totalImages: 4,
    },
    { 
        id: 14,
        name: 'Kaba Kaba',
        slug: "kaba-8are",
        price: '13',
        size: '8',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/kaba/8are/img1.jpg',
        img: '/image/terrains/kaba/8are',
        totalImages: 4,
    },
    { 
        id: 15,
        name: 'Kaba Kaba',
        slug: "kaba-12are",
        price: '12',
        size: '12',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/kaba/12are/img1.jpg',
        img: '/image/terrains/kaba/12are',
        totalImages: 4,
    },
    { 
        id: 16,
        name: 'Cepaka',
        slug: "cepaka-15are",
        price: '13',
        size: '15',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/cepaka/15are/img1.jpg',
        img: '/image/terrains/cepaka/15are',
        totalImages: 4,
    },
    { 
        id: 17,
        name: 'Nyanyi',
        slug: "nyanyi-15are",
        price: '16.5',
        size: '15',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Nyanyi/15are/img1.jpg',
        img: '/image/terrains/Nyanyi/15are',
        totalImages: 4,
    },
    { 
        id: 18,
        name: 'Buwit',
        slug: "Buwit-16are",
        price: '11.5',
        size: '16',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Buwit/16are/img1.jpg',
        img: '/image/terrains/Buwit/16are',
        totalImages: 3,
    },
    { 
        id: 19,
        name: 'Munggu',
        slug: "Munggu-18are",
        price: '16.5',
        size: '18',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Munggu/18are/img1.jpg',
        img: '/image/terrains/Munggu/18are',
        totalImages: 3,
    },
    { 
        id: 20,
        name: 'Cepaka',
        slug: "cepaka-19are",
        price: '11.5',
        size: '19',
        time: 'Leasehold 25 ans',
        zone: 'Jaune',
        image1: '/image/terrains/cepaka/19are/img1.jpg',
        img: '/image/terrains/cepaka/19are',
        totalImages: 4,
    },
    { 
        id: 21,
        name: 'Canggu',
        slug: "canggu-20are",
        price: '10',
        size: '20',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/northcanggu/20are/img1.jpg',
        img: '/image/terrains/northcanggu/20are',
        totalImages: 3,
    },
    { 
        id: 22,
        name: 'Buwit',
        slug: "Buwit-25are",
        price: '9.5',
        size: '25',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Buwit/25are/img1.jpg',
        img: '/image/terrains/Buwit/25are',
        totalImages: 4,
    },
    { 
        id: 23,
        name: 'Buwit',
        slug: "Buwit-25are",
        price: '10',
        size: '25',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Buwit/25are-10mil/img1.jpg',
        img: '/image/terrains/Buwit/25are-10mil',
        totalImages: 4,
    },
    { 
        id: 24,
        name: 'Buwit',
        slug: "Buwit-28are",
        price: '10',
        size: '28',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Buwit/28are/img1.jpg',
        img: '/image/terrains/Buwit/28are',
        totalImages: 4,
    },
    { 
        id: 25,
        name: 'Munggu',
        slug: "Munggu-35are",
        price: '18.5',
        size: '35',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Munggu/35are/img1.jpg',
        img: '/image/terrains/Munggu/35are',
        totalImages: 4,
    },
    { 
        id: 26,
        name: 'Nyanyi',
        slug: "nyanyi-42are",
        price: '20.5',
        size: '42',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Nyanyi/42are/img1.jpg',
        img: '/image/terrains/Nyanyi/42are',
        totalImages: 4,
    },
    { 
        id: 27,
        name: 'Cemagi',
        slug: "cemagi-50are",
        price: '23.5',
        size: '50',
        time: 'Leasehold 25 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Cemagi/50are/img1.jpg',
        img: '/image/terrains/Cemagi/50are',
        totalImages: 4,
    },
    { 
        id: 28,
        name: 'Nyanyi',
        slug: "nyanyi-53are",
        price: '26.5',
        size: '53',
        time: 'Leasehold 30 ans',
        zone: 'Jaune',
        image1: '/image/terrains/Nyanyi/53are/img1.jpg',
        img: '/image/terrains/Nyanyi/53are',
        totalImages: 4,
    },
    { 
        id: 29,
        name: 'Tanah Lot',
        slug: "tanahlot-53are",
        price: '9',
        size: '53',
        time: 'Leasehold 22 ans',
        zone: 'Jaune',
        image1: '/image/terrains/tanahlot/53are/img1.jpg',
        img: '/image/terrains/tanahlot/53are',
        totalImages: 4,
    },
]